language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov=zeugma/
after_success:
  - coveralls
deploy:
  provider: script
  script: python setup.py sdist && twine upload -u __token__ -p $PYPI_TOKEN dist/* 
  on:
    tags: true
