language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install Cython
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov=zeugma/
after_success:
  - coveralls
